#ifndef __IMAGINEDB_ENGINE_CONTAINERS_NUMBER_OPERATORS__
#define __IMAGINEDB_ENGINE_CONTAINERS_NUMBER_OPERATORS__

#include "number.hpp"



#endif /* __IMAGINEDB_ENGINE_CONTAINERS_NUMBER_OPERATORS__ */